### PR TITLE
1454 fix case with no history

### PR DESCRIPTION
**Pull request by trystant**
In your PR did you:

  - [ X ] Include a description of the changes? A fix for a case with no history so that a page displays 
instead of an error.
  - [ X ] Mention the issue the PR addresses? Fixes issue #1454 
  - [ X ] Include screenshots of any changes to the UI?

screenshot 2018-04-18 at 05 38 03

  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ X ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Quick question - this wasn't supposed to change those gemset and version files, was it?

**Comment by rlgreen91** [comment]
@trystant can you resolve these conflicts real quick?  Also, are there supposed to be changes to the gemset and version?

**Comment by trystant** [comment]
If this doesn't work, it may make sense to duplicate the PR with a new branch & run with that.

**Comment by rlgreen91** [comment]
Yeah, we may have to do that.

**Comment by trystant** [comment]
I figured it out.

**Pull request closed without merging**
