### PR TITLE
#2435 Moved buttons to agency form partial 

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [X] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

screenshot from 2018-09-17 12-11-05
screenshot from 2018-09-17 12-10-51

### CODE REVIEW

**Comment by rlgreen91** [comment]
The styling for the show back buttons in the update form is incorrect based on the screenshot.

**Comment by rlgreen91** [comment]
Also, the back button is the same for both actions.  It's really just the text on the submit button that will change based on the action - "create agency" vs "update agency"

**Comment by danuluma** [comment]
screenshot from 2018-09-22 03-04-40

**Comment by rlgreen91** [comment]
@danuluma Uh, what's up with the extra show button?  It's fine if this is an older screenshot and you removed it, just let me know.

**Comment by danuluma** [comment]
The 'show' and 'back' actions were there originally as links side by side. I simply converted them to buttons and placed the back button in a similar position as the one on 'create' page,, for consistency. As for the show button , I thought it would look better on the left side, and applied styling similar to the 'update agency button'

**Comment by danuluma** [comment]
The 'show' button returns to the agency without updating, while the 'back' button returns to the agencies list

**Comment by danuluma** [comment]
I can, however, remove it if need be

**Comment by rlgreen91** [comment]
Yes, can you remove the show button?  The back button is fine.  Also there's a conflict - please merge master into this branch.

**Comment by danuluma** [comment]
screenshot from 2018-09-26 20-43-07

**Pull request merged**
