### PR TITLE
for #2721 not sure how @ethnicities got to be nil, this fix adds the …

### PR DESCRIPTION
**Pull request by campgurus**
…collection back so the edit/new forms perform properly

In your PR did you:

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@campgurus are you going to address @trystant's comments?

**Comment by campgurus** [comment]
I will fix these. Btw, I do not receive notifications of these comments, so I only see the when I come back to the PR page, which is why my responses are sporadic.

**Comment by rlgreen91** [comment]
But it's your PR, lol?  How do you not get a notification when someone makes a comment on it?

**Comment by rlgreen91** [comment]
@trystant Merge in master.

**Pull request merged**
