### PR TITLE
#1921 Added undo and redo links to agency controller 

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@danuluma You might have to redo this one - we're actually making changes to how the undo functionality works to make it easier to add to other models.  As you can see here, this is kind of messy.  I'll find another issue you can work on in the meantime.

**Comment by danuluma** [comment]
I agree @rlgreen91, I had actually created a versions controller in the previous pr to reduce repetitive code.

**Comment by danuluma** [comment]
I've seen the new task. Thanks

**Comment by rlgreen91** [comment]
Closing until other work is completed.

**Pull request closed without merging**
