### PR TITLE
3144 remove ahoy

### PR DESCRIPTION
**Pull request by trystant**
In your PR did you:

  - [X] Include a description of the changes? I removed all traces of ahoy from the codebase with the exception of the tables, since they still have data that can be used & incorporated into a new package.
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [X] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@trystant I understand removing the Ahoy related code, but why do we need to remove all analytics code?

**Comment by trystant** [comment]
@rlgreen91 I want to remove this analytics code from `master` because it's not being used currently. An analytics solution with either SumoLogic or MixPanel will need to be readjusted. When that solution works, we can use `git` history to bring the analytics specs back and then create a clean implementation.

**Comment by rlgreen91** [comment]
@trystant Ok, thanks.  Once the tests pass again I'll approve so you can merge.

**Comment by trystant** [comment]
@rlgreen91 FWIW, I also want to remove the Maps code as well until a new(er) implementation is in place.

**Comment by rlgreen91** [comment]
> @rlgreen91 FWIW, I also want to remove the Maps code as well until a new(er) implementation is in place.

That sounds good, just put it in a separate PR please.

**Pull request merged**
