### PR TITLE
updated mailboxer gem to version ~> 0.14

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@danuluma Hey, so we still want to point to the source of the gem listed in the Gemfile previously - however, we just want to grab the highest version possible from that source.

**Comment by danuluma** [comment]
Noted @rlgreen91 

I've changed it back to the original GitHub source and used the latest version available there (v 0.12.5 as ~> 0.12)

I've noticed, however, that its a fork from "https://github.com/mailboxer/mailboxer" - the original mailboxer gem repo and it's several commits and releases behind

**Comment by rlgreen91** [comment]
I see.  In that case, go ahead and use the original source like you planned.  Looking through the repos now, I don't see any major divergences that we need to worry about.

Please also merge master into this branch.

**Comment by rlgreen91** [comment]
@danuluma Just as a heads up this is still pointing to the fork.  You can change it back to following the original gem source.

**Comment by danuluma** [comment]
Hi, @rlgreen91. I pointed it to the official one on rubygems.org. It's currently at version 0.15.1, but this requires rails >= 5.0.0 The highest version supported by rails 4.2 is v0.14.0

**Comment by danuluma** [comment]
That's the version I updated to.

**Comment by rlgreen91** [comment]
@danuluma Thanks!  Making a note to upgrade after we finish our upgrade to Rails 5.

**Pull request merged**
