### PR TITLE
#2318 moved faker gem to development and test group

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@danuluma did you run `bundle install` after changing this?  You need to updated `Gemfile.lock`.

**Comment by danuluma** [comment]
I've updated it by deleting ```Gemfile.lock``` and running bundle again to fetch the gems. I don't know if that is okay

**Comment by danuluma** [comment]
Or should I revert

**Comment by rlgreen91** [comment]
No worries, this is fine.  I just needed you to run `bundle install` to make sure we captured any changes there.

**Pull request merged**
