### PR TITLE
Add Timeago.js

### LINKED ISSUE #3151: Add and use timeago js library
Currently, we use the `time_ago_in_words` helper to format things like "2 days ago".  In the future, it would be better to do this conversion client side rather using a rails helper to save on time and avoid stale values in cached pages.  This issue involves installing [this library](https://timeago.org/) via the vendor assets directory and replacing the helper with the appropriate Javascript.

### PR DESCRIPTION
**Pull request by mariogmz**
Closes #3151

# Changes
- Add timeago.js library to vendor assets.
- Added a `span` with `time-ago-label` so timeago script can update dates.

### CODE REVIEW

**Comment by mariogmz** [comment]
@rlgreen91 and @StlMaris123 can you please review this?

**Comment by mariogmz** [comment]
@rlgreen91 can you help me with the CI tests, seems that something is failing but it's not related to my changes I guess.

**Comment by rlgreen91** [comment]
Hi @mariogmz, thank you for your contribution!  You don't need to worry about CI - that's an issue with Travis.  Can you post a screenshot of how this looks?  I'm running the code locally and no value shows up as expected.

**Comment by mariogmz** [comment]
@rlgreen91 give some time to rework on this, I'm having trouble with my aws account.

**Comment by rlgreen91** [comment]
@mariogmz can you fix this merge conflict before I review again?

**Comment by mariogmz** [comment]
@rlgreen91 sure!

**Comment by rlgreen91** [comment]
HI @mariogmz, are you going to be able to finish this soon?

**Pull request closed without merging**
