### PR TITLE
Update gemfile

### PR DESCRIPTION
**Pull request by jessecalton**
Update gemfile to include paper_trail-association_tracking gem

In your PR did you:

  - [ ] Include a description of the changes?
  - [ ] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hi @jessecalton, thanks for your contribution!  Did you run the installer as well?  There should be at least changes to the `structure.sql` file.

**Comment by jessecalton** [comment]
sure, I can do that. I was on a weak connection so I couldn't clone the repo locally.

**Comment by jessecalton** [comment]
@rlgreen91 looks like it's gonna be a little more complicated than I initially anticipated. I'll need an AWS and Mailchimp account, which will take some time. Feel free to loan the issue to someone else, but I may be able to take another stab at it tomorrow. I'm on a new machine so it took me a while to get the Ruby on Rails environment going -_- Thanks for the quick feedback!

**Comment by rlgreen91** [comment]
@jessecalton Is it the warnings coming from Travis?  If that's the case, feel free to disregard and proceed.

**Comment by rlgreen91** [comment]
@jessecalton Are you still interested in working on this PR?  If so, please comment by Saturday, December 22, or I will close this PR.

**Pull request closed without merging**
