### PR TITLE
Change jurisdiction enum to jurisdiction_type#1343[wip]

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
This pr involves a series of other steps that have been discussed on  #1332
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , @trystant some tests are failing because they are related to the gem, should I do the other issues on this pr or another one?

**Comment by trystant** [comment]
@StlMaris123 what are the specific error messages that you're receiving?

**Comment by trystant** [comment]
Is this [Travis](https://travis-ci.org/EBWiki/EBWiki/builds/375806113) build the one in question?

**Comment by rachaelkiteme** [comment]
Hello @StlMaris123 I did same issue some time back you can check on the closed issues #1448 comment given by @rlgreen91 on the same.

**Comment by trystant** [comment]
@Stl

**Comment by StlMaris123** [comment]
Hi Mark,  yes the issue is on Travis

**Comment by rlgreen91** [comment]
Yeah, so I'll explain more when I get to a computer later, but don't start
with this issue. Look at the project listed on the issue page. Click on the
link to go to the project page - there should be a note explaining that the
issues have to be completed in the order listed. I can't remember how many
there are, but this should be the last one. You can still work on this in
general, you just can't start with this particular issue. You have to start
with whatever I listed first, changing a column name or something. I'll
follow up more later.

**Comment by StlMaris123** [comment]
Okay no worries, I will follow it

**Comment by rlgreen91** [comment]
Ok, I'm here!  So basically, we're handling enums for the `Agency` model using a gem, and we'd like to switch to using built-in functionality in Rails and PostGres.  As I mentioned in my last comment, on the issue page, there's a section showing what projects and milestones it belongs to - that section is on the right, below the labels.  If you click that, it takes you to this [project page](https://github.com/EBWiki/EBWiki/projects/5).  That has two notes explaining where I got the process we'll be following from and that the issues have to be completed (in this case merged) in the order listed.  I'll add a note in bold on each of the issues, but outside of that there's nothing more I can really do to indicate when a group of issues needs to be done in a particular order.  Hope that helps.

**Comment by rlgreen91** [comment]
Ah, I should have asked - given that, do you want to just go ahead and close this PR?  That way by the time we get to it you don't have to worry about merge conflicts from other changes.

**Comment by StlMaris123** [comment]
No need to close it, I will just revert the changes and proceed from there

**Comment by StlMaris123** [comment]
Rachel created a similar pr so i will go a head and close this one

**Pull request closed without merging**
