### PR TITLE
Article to case

### PR DESCRIPTION
**Pull request by trystant**
Turned these changes into a pull request to check the travis & codeclimate results.

### CODE REVIEW

**Comment by trystant** [comment]
So `rubocop` on my local dev environment results in:

```
164 files inspected, 494 offenses detected
```

and Codeclimate on the associated PR has 51 issues at least.

So there's more work to do.

**Comment by trystant** [comment]
```
164 files inspected, 491 offenses detected
```

**Comment by trystant** [comment]
```
164 files inspected, 481 offenses detected
```

**Comment by trystant** [comment]
```
164 files inspected, 397 offenses detected

**Comment by trystant** [comment]
```
163 files inspected, 345 offenses detected
```

**Comment by trystant** [comment]
```
163 files inspected, 255 offenses detected
```

**Comment by trystant** [comment]
```
163 files inspected, 228 offenses detected
```

**Comment by trystant** [comment]
```
163 files inspected, 213 offenses detected
```

**Comment by trystant** [comment]
```

**Comment by trystant** [comment]
Latest Rubocop run locally.
[rubocop.log](https://github.com/EBWiki/EBWiki/files/1798454/rubocop.log)

**Comment by rlgreen91** [comment]
Some of these aren't too bad, and will be addressed as we do some refactoring.

**Comment by trystant** [comment]
```
162 files inspected, 175 offenses detected
```

**Comment by trystant** [comment]
```
162 files inspected, 150 offenses detected
```

Closer & closer.

**Comment by trystant** [comment]
```
162 files inspected, 121 offenses detected
```

This is it for the time being. The next stages include:

**Comment by trystant** [comment]
So there is a version of this on staging  & this branch has been merged into master.

**Pull request merged**
