### PR TITLE
#2115 updated the button colours on case show view

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@danuluma the change to the Gemfile should not be here.  Additionally, why did you create a new class for the button?  Was it not possible to style it using existing classes?

In the future, if you are making changes to the UI please include a screenshot.

**Comment by danuluma** [comment]
The faker gem was still in the test group and rails server couldn't start if it wasn't in the development environment, hence I moved it there. There's a pr for that but it had not yet been merged into master.

**Comment by danuluma** [comment]
The classes already available are default bootstrap classes, I'm not sure if they have been used in other views and since the changes were intended for the cases view only, I thought it better to create a new class and define its styles in the cases.scss

**Comment by danuluma** [comment]
screenshot from 2018-09-04 04-58-01
screenshot from 2018-09-04 04-57-53

**Comment by danuluma** [comment]
Sorry, forgot to include the screenshots in the pr. I used the $color-orange variable already defined, but it appears to me more of red than orange

**Comment by rlgreen91** [comment]
@danuluma that PR has been merged into master, so please update this branch.  With regard to the buttons, we do apply this styling on other pages, so I would check how they handle it and replicate/share styles as much as possible.  I'm not sure what's up with your colors though - it's definitely more orange when I see that color, and that's true for multiple computers.

**Pull request merged**
