### PR TITLE
Fix documentation relative links to files

### PR DESCRIPTION
**Pull request by jaimevelaz**
In your PR did you:

  - [X] Include a description of the changes?

Looking at the documentation to setup the environment I found that the relative links found inside `docs` folder were pointing to `docs/FILE` which broke them. This PRs changes that relative links to work properly, also it fixes some typos found.

  - [ ] Mention the issue the PR addresses?

There's no issue about this, I would he happy to create one if required.

  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by managedkaos** [comment]
Great minds think alike.  I was fixing the same in #3704 👍

**Comment by jaimevelaz** [comment]
> Great minds think alike. I was fixing the same in #3704 👍

Didn't check the opened PR, sorry for the possible noise! I'm totally fine with closing this so all changes are done in #3704

**Comment by managedkaos** [comment]
I think you still have some valid changes there that I don't have in mine. 👍

**Comment by managedkaos** [comment]
If both PRs are applied we will get to a better result. 😄

**Comment by rlgreen91** [comment]
Sorry @jaimevelaz, it looks like all of the changes you made are covered in #3704.  Thank you for submitting a PR though!  I believe this will still count for Hacktoberfest, plus we have other relatively quick issues that you can pick up as well.

**Pull request closed without merging**
