### PR TITLE
Shashank76 patch 3

### PR DESCRIPTION
**Pull request by shashank76**
#2646

### CODE REVIEW

**Comment by rlgreen91** [comment]
@shashank76 I'm assuming that you came across this link on how to add password updates: https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password.  Looking at that, I prefer Solution 1 since that more closely matches what we already do.  Additionally, please add language to the mailer on who to contact if the user did not change their password as per the issue.

**Comment by shashank76** [comment]
> @shashank76 I'm assuming that you came across this link on how to add password updates: https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password. Looking at that, I prefer Solution 1 since that more closely matches what we already do. Additionally, please add language to the mailer on who to contact if the user did not change their password as per the issue.

**Comment by rlgreen91** [comment]
Please add language in the email template on who to contact if they did not request a password change.  Additionally, in the text "password" should not be capitalized.

**Comment by rlgreen91** [comment]
@shashank76 Will you be able to complete the changes in this PR?  If so, please respond by December 15. Otherwise, I will close this PR.

**Pull request closed without merging**
