### PR TITLE
#2677 Add newline between link fields on case form

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [x] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by danuluma** [comment]
> Hi @danuluma can you attach a screenshot of the changes?

Ahh sorry about that, let me attach it

**Comment by danuluma** [comment]
### Before

screenshot from 2018-12-08 23-02-56

**Comment by danuluma** [comment]
### After

screenshot from 2018-12-08 23-02-11

**Comment by rlgreen91** [comment]
Perfect!

**Pull request merged**
