### PR TITLE
Changed route of maps/index to maps #2493

### PR DESCRIPTION
**Pull request by manasbedmutha98**
In your PR did you:

  - [x] Include a description of the changes? Changed in config/routes.rb line 6
  - [x] Mention the issue the PR addresses? Updates route of maps
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by trystant** [comment]
@manasbedmutha98 This is a result of not having an AWS bucket set up for Travis. Let me look into something...

**Comment by manasbedmutha98** [comment]
@trystant , so what do I do now? I have no knowledge about S3. How do I go about the PR?

**Comment by rlgreen91** [comment]
@manasbedmutha98 did you follow the set up guidelines?  That explains how to set up the environment, including S3, to avoid this.

**Comment by rlgreen91** [comment]
@manasbedmutha98 were you able to verify locally that the specs still pass?  That's the only thing keeping this PR from being merged.

**Comment by manasbedmutha98** [comment]
@rlgreen91, Sorry I have exams till tomorrow. Will be only able to do it then. Sorry for the delay. In the mean time, in case anyone else wants to take it up, please feel free.

**Comment by rlgreen91** [comment]
@manasbedmutha98 that's no problem, I just wanted to make sure that I explained exactly what needed to be done.  Feel free to take your time.

**Comment by rlgreen91** [comment]
This fix has been merged as part of another PR.  As such, I will close this.

**Pull request closed without merging**
