### PR TITLE
Update paper_trail gem to 5.2.3 #1977

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
Update paper_trail gem to 5.2.3 
Solves #1977
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I have reverted the changes you had requested, they were having the failure ` #<Double (anonymous)> received unexpected message :whodunnit with (no args)
`

**Comment by rlgreen91** [comment]
@StlMaris123 you still need to make the changes listed in the issue, otherwise the app will break on this going forward.  If it causes a test to fail put the result here or let it fail in CI.  Otherwise, I can't provide suggestions on how to fix it.

**Comment by StlMaris123** [comment]
I have struggled with this issue, so I put as pending. I tried googling but could not find a solution: 
```ActiveRecord::StatementInvalid:
       PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
       : SAVEPOINT active_record_2
```

**Comment by rlgreen91** [comment]
Agh, I actually came across this maybe a couple of weeks ago?  The error is kinda misleading, but basically if PostGres can't execute a SQL statement due to invalidity, then it just automatically aborts all future transactions that occur in the same connection.  When exactly where you encountering this?  If you were running the server locally, or the console, or debugging during a test, quitting and restarting should be enough to stop it so you can fix the SQL.  If not, let me know and we can look some more.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , the error occurs when running the tests. It is the only spec failing

**Comment by rlgreen91** [comment]
Ok.  There's some other stuff going on with history pages in general, so we'll just leave this as pending and merge.

**Pull request merged**
