### PR TITLE
Create a null case object #2148

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
Create a null case object 
- Solves #2148
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 I did a few tweaks in this pr:
1. I created the null object in a folder called `null`, the `null_objects` had an issue Uninitilaized constant error.
2. I called the method in the history action instead of calling it on the case object, because that mean i define it in the case model.
What do you think of the approach

**Comment by rlgreen91** [comment]
Hey, so what was the error about Uninitialized constant?  You shouldn't have gotten something like that.  If you had a file `app/null_objects/case.rb`, then this should have worked:

```
module NullObjects
  class Case
    ...
  end
end
```

Also, while your thoughts on `check_case_presence` are good, we don't want to do quite that because we do a redirect (or should be) if the case doesn't exist.  So for right now we should just replace the versions check.

**Comment by rlgreen91** [comment]
@StlMaris123 Please merge master into this branch.  Additionally, there should now be a `null_objects` directory.  Please be sure to add a spec as well.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I found out how we were getting the `uninitialized constant NullObjects::Case`, as explained here https://github.com/rails/rails/issues/14382, the nuul_objects is treated as root_path and therefore cannot be used for name spacing.

**Comment by rlgreen91** [comment]
That particular issue isn't relevant here, given that the issue there was not following naming conventions.  Not to mention that we've already added a null_objects directory. :)

I think you're running into issues here because we're trying to replace too much with null object.  For right now, if we find that `this_case` is empty, then we should set `case_history` to `nil`.  Then, when it comes time to see if the case has any versions, that's when we either return the case or the null case object based on the result.  Hopefully that should fix the error.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , before we were looping through case_history only if a case has versions. But now if a case has no versions or its empty. We are returning Case.none.
The tests are failing because we are trying to loop through Case.none

**Comment by rlgreen91** [comment]
I see.  Hmm, in that case let's trying adding a `versions` method to the null case object that returns `Case.none`

**Comment by rlgreen91** [comment]
Please merge master into this branch.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , issue here is that 
`Case.none` gives `#<ActiveRecord::Relation []>` , so trying to called versions on its instance will  raise```NoMethodError (undefined method `versions' for #<ActiveRecord::Relation []>)```

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , what is the way forward with this?

**Comment by rlgreen91** [comment]
For right now, let's change the code in the view to check `if @case_history.blank?`.  Once we add presenters we can clean that logic up a bit.

**Pull request closed without merging**
