### PR TITLE
3793 update carrierwave gem

### PR DESCRIPTION
**Pull request by debashis-biswal**
Update carrierwave gem
Fixes: #3793 

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hi @debashis-biswal, so this is like your other PRs, where after making a change in the Gemfile, you'll want to run `bundle install` to force the Gemfile.lock to regenerate properly.

**Comment by debashis-biswal** [comment]
> Hi @debashis-biswal, so this is like your other PRs, where after making a change in the Gemfile, you'll want to run `bundle install` to force the Gemfile.lock to regenerate properly.

@rlgreen91 I will do that. Thanks

**Comment by rlgreen91** [comment]
Hi @debashis-biswal, can you resolve the merge conflicts on this?  Thanks

**Comment by debashis-biswal** [comment]
> Hi @debashis-biswal, can you resolve the merge conflicts on this? Thanks

Sure. I will resolve the merge conflicts.

**Review by Sameera1994 — APPROVED** [review]

**Review by Sameera1994 — APPROVED** [review]

**Comment by rlgreen91** [comment]
Hey @debashis-biswal I wanted to come back to this, since this seems like the one PR you submitted that wasn't merged.  We actually ran into a security issue with Carrierwave, and dependabot handled the update as part of that.  So I'll just close this one out.

**Pull request closed without merging**
