### PR TITLE
Add agencies guide to contributing section 

### LINKED ISSUE #1574: Add section on agencies to Guide to Contributing
Note: This is issue 3 of 3, and the requested changes must be merged before you can move to the next one in the project.

In the Guide to Contributing to EBWiki, add a section titled "Agencies".  This section should contain two subsections: one for adding an agency and one for updating an agency.  Have a heading for the section, and collapse the subsections by default - selecting the corresponding heading should expand and collapse the subsection.

### PR DESCRIPTION
**Pull request by rachaelkiteme**
In your PR did you:
Fixes #1574 

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rachaelkiteme** [comment]
For the Agencies, I didn't get the tab to add, view or edit the Agencies. The only way I can view them is by searching https://ebwiki.org/agencies directly.
Is there a way out for this?

**Comment by rlgreen91** [comment]
Let me check - there were specific reasons as to why all you can really do is get to the edit page for this.

**Comment by rlgreen91** [comment]
@rachaelkiteme So, for right now, I would just show how you can add an agency when editing a case - right now, if you go to edit a case, you should see a link to add a new agency in the agency section.

**Comment by rachaelkiteme** [comment]
Done.

Suggestion, guess we should have add agency section while creating a new
case and better way to edit agency rather than visiting
https://ebwiki.org/agencies
What do you think?

Regards
Rachael

**Comment by rlgreen91** [comment]
@rachaelkiteme looks good.  Let's talk more about agencies in Slack so I can close this.

**Pull request merged**
