### PR TITLE
Add migration dropping calendar_events table

### LINKED ISSUE #4047: Remove calendar events table from database
Remove the current `calendar_events` table from the database.  

Dev Note: You do not have to remove the associated model file.

### PR DESCRIPTION
**Pull request by luhova**
Fixes #4047 

In your PR did you:

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Add and/or update specs for your code?
  - [ ] Update the release tasks script to reflect tasks that should run when deploying to staging or production?

### CODE REVIEW

**Comment by luhova** [comment]
I am not sure how can I update the db/structure.sql file. When I ran `rails db:migrate` it created a `schema.rb` file, but I see that the rspec check here doesn't pass. Any suggestions on how can I fix this?

**Comment by rlgreen91** [comment]
@luhova Yes, this is an issue with the change in configs as we upgraded to 5.2.  What you'll need to do is roll-back your migration, and then add this line to `config/application.rb`:

```config.active_record.schema_format = :sql```

Then when you run the migration, it should update `structure.sql` like expected, and you can toss the schema file.

**Comment by luhova** [comment]
@rlgreen91 wohoo, I followed your advise and all checks passed now :rocket:

**Review by rlgreen91 — APPROVED** [review]

**Comment by rlgreen91** [comment]
Great!

**Comment by rlgreen91** [comment]
@luhova for some reason I can't assign that other issue to you - I invited you to the project so you should be able to assign the issue to yourself once you join.  Here's a link to it: https://github.com/EBWiki/EBWiki/issues/4055

**Pull request merged**
