### PR TITLE
validate url presence solves#1658 

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
This Pr validate url presence
- Solves issue  #1658
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , Am kindly requesting for more information on this issue on some this that are not clear:

1. Do we have to create a link creation action?
2. Is the link creation form in `new cases form` the one we are using to create the links?
3. At what point will the link be created? Should we have a separate `submit` button for the links on `new cases form`

1.

**Comment by rlgreen91** [comment]
So, the only place we create links is as part of creating or editing cases.  We use Simple Form helper `simple_fields_for` which allows us to create the links as part of creating cases.  See [here](https://github.com/plataformatec/simple_form) and [here](http://api.rubyonrails.org/v5.2.0/classes/ActionView/Helpers/FormHelper.html#method-i-fields_for) for more details.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , this issue has really helped to understand more on associations....also more on `gem 'simple_form'` and `gem 'cocoon'`

**Comment by rlgreen91** [comment]
That's good to hear!  This looks good, so I'll go ahead and merge.

**Pull request merged**
