### PR TITLE
Fixed page button misalignment

### PR DESCRIPTION
**Pull request by ArushiSinghal**
Issue #1120 
This pull request is to fix the page misalignment with the first suggestion.

### CODE REVIEW

**Comment by rlgreen91** [comment]
As I mentioned in PR #1300 - one PR for one fix, more or less.  I suspect you'll just keep updating this one, so I left it open.  Be sure to check what the issue is with Travis CI if it fails again after you update the PR.

**Comment by ArushiSinghal** [comment]
Hello, @rlgreen91 we will try to fix this issue.

**Comment by rlgreen91** [comment]
Hi @ArushiSinghal, do you need any help with the changes that I requested?  Is there anything blocking your progress?

**Comment by simransinghal** [comment]
@rlgreen91 Hi
@ArushiSinghal and I are busy with our university exams, so is not able to send the updated pull request. Will be able to finish this task in the coming week.

Thanks for helping.

**Comment by rlgreen91** [comment]
Hi @ArushiSinghal!  Just to give you a heads up: so, I go into more detail in the Slack channel, but basically Travis doesn't work well with environment variables coming from forks.  What you'll need to do is make a topic branch with EBWiki and then push code from there.  I believe you're listed as a collaborator, but if it gives you a permission denied error when you try to push code, just let me know.

**Comment by simransinghal** [comment]
ok @rlgreen91 
Thanks for the information

**Comment by rlgreen91** [comment]
Hi @ArushiSinghal just as a headsup - when you go to do this and pull down the master branch again, you'll notice that we've renamed the `article` model to `case`.

**Comment by rlgreen91** [comment]
This is addressed in PR #1569, so I'll be closing this.

**Pull request closed without merging**
