### PR TITLE
WIP remove weird dots underneath stars on required fields in forms

### PR DESCRIPTION
**Pull request by rachaelkiteme**
This pr removes weird dot on new and edit forms

### CODE REVIEW

**Comment by rlgreen91** [comment]
Yes, so I want to remove the dots, but those fields should still be required.  Additionally, don't push up the changes to your `config/database.yml` if you just needed to uncomment those lines for configuration purposes.

**Comment by rachaelkiteme** [comment]
Great! have checked it out, its a nice tutorial let me try the fixes. Thank
you so much Rachel

Regards
Rachael

**Comment by rachaelkiteme** [comment]
Hi @rlgreen91,

It worked so well the dots are out. Thank you for the tutorial.

Am having some difficulty when I uncommented the lines in config/database.yml.
Once I uncomment and run rails server it aborts the process.

Please advice according.

Thank you.

Regards
Rachael

**Comment by rachaelkiteme** [comment]
This travis-ci built error!

**Comment by rlgreen91** [comment]
@rachaelkiteme please add screenshots showing the change.  Also, remember to make this change for all forms, not just the ones for a user.

So, I'm not quite sure what you mean about uncommenting those lines causing a rails server issue - did you do that as part of your setup process?  You should have had to do that only if you're using a Windows computer.

**Comment by rlgreen91** [comment]
@rachaelkiteme Do you need any help with the changes I requested?  Is there anything blocking you?

**Comment by rachaelkiteme** [comment]
Hi Rachel,

Am doing great, I made the changes as requested, I updated the forms.scss
file that works for all forms. But am stack with github, travis-ci error
and guess I made some mistakes while committing was planning to meet
@Stlmaris123 my partner to guide me on what to do. Case of anything will
let you know. Thanks for your concert

Regards
Rachael

**Comment by rlgreen91** [comment]
@rachaelkiteme do you mind trying something for me?  Can you recreate make a second PR with these changes, but this time, don't create your own fork?  Just pull down the EBWiki repo, and create a branch within that directory.  I think that may be the key to getting past this Travis error.

**Comment by rachaelkiteme** [comment]
Okay, I will definitely do that. Thank you so much for getting back to me.


Regards
Rachael

**Comment by StlMaris123** [comment]
HI @rlgreen91 ,
I wanted to steal the idea you gave @rachaelkiteme by pushing my branch directly to EBwiki but we do not have permissions to do that
screenshot from 2018-03-14 09-37-40

**Comment by rachaelkiteme** [comment]
Yeah true @rlgreen91 am getting same error as @StlMaris123

Regards
Rachael

On Wed, Mar 14, 2018 at 9:38 AM, StellaMaris Njage <notifications@github.com

**Comment by rlgreen91** [comment]
I added y'all as collaborators, so see if it'll let you push again.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I still do not have permissions

**Comment by rachaelkiteme** [comment]
Mine worked so well and all checks passed, Thank you so much @rlgreen91.


​


Regards
Rachael

**Pull request closed without merging**
