### PR TITLE
Redirect /article to /case

### PR DESCRIPTION
**Pull request by trystant**
- Gemfile - Updated paper_trail version to 4.2.0

- Gemfile.lock - Locked version of the file

- config/routes.rb - Added routes to redirect /article links to /case

- spec/requests/articles_redirect_spec.rb - Specs to confirm that the
  article redirect is in place.

Updates #1437

In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [X] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
What's up with the changes to `cases_controller_spec.rb`?

**Comment by campgurus** [comment]
It looks like the spec changes were just additional spaces between lines, no?  Can we try to merge this ?

**Comment by rlgreen91** [comment]
Hmm, there was something else there I thought.  Anyways, I think @trystant said there was one more thing he planned to do on this one.  Is that still true?  Otherwise I will merge.

**Comment by trystant** [comment]
I think that this is ready to go now.

**Pull request merged**
