### PR TITLE
refactor new method in conversations controller solves #1112

### PR DESCRIPTION
**Pull request by StlMaris123**

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hello @rlgreen91 , I was looking through the rails guides on how to use the select method.  Based on this example `select("post", "person_id", Person.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })`, do we need to redefine the `@other_users` yet we have already defined in the controller?

**Comment by rlgreen91** [comment]
Why did you get rid of `multiple = "multiple"`?

I'm not sure what you mean by redefine - you should be able to just pass in `@other_users` as the collection.  Can you clarify that?

Also, make sure that you add a description for the changes to the PR, and that CI passes.

**Comment by rlgreen91** [comment]
Oh, also, you'll want to pass for each user the name then the ID, not the other way around.

**Comment by StlMaris123** [comment]
What is the function of  `{}` after `@other_users`? I understood the logic I had earlier on asked

**Comment by StlMaris123** [comment]
@rlgreen91 I kindly need your help on the Travis-Ci, Locally, everything seems to be working well

**Comment by rlgreen91** [comment]
I wouldn't recommend adding those config files to .gitignore - then you'll miss changes that do need to be made to the files.  It's also what's probably causing Travis to fail - it doesn't see your config files, which define some things like CarrierWave credentials.  I'd add it back and try again - if you look back at the documentation on setup you should see how you can add the credentials without needing to change the files.

With regard to `{}`, I suggest looking up the `form_for` and `select` methods to see what the arguments correspond to first.

**Comment by rlgreen91** [comment]
@StlMaris123 why is there still an addition to .gitignore?  That file should not have changed at all.  That's what keeps breaking CI.

**Comment by StlMaris123** [comment]
Hi Rachel, that is where I have set up the AWS env variables.  Where should
we set them?

**Comment by rlgreen91** [comment]
I'm not sure I follow - did you put the credentials directly in the file?  You shouldn't do that - they should be saved as environment variables.  The documentation about setting up your environment explains how to do that without exposing the credentials.

**Comment by StlMaris123** [comment]
On S3.rb and sitemap.rb we have those two lines of code
```
   aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
   aws_secret_access_key: ENV['AWS_SECRET_KEY_ID']
```

Then On the file I ignored I set up the variables:
``` 
   ENV['AWS_ACCESS_KEY_ID' = 'xxxxx'
   ENV['AWS_SECRET_KEY_ID'] = 'aaaaa'
```

Without them on the command `rake db:migrate` , i was getting the error `argumenterror: missing required arguments: aws_access_key_id, aws_secret_access_key`

**Comment by rlgreen91** [comment]
Ah, ok, so that's not the correct setup.  See this [link](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps) for information on setting environment variables.  The sections that are applicable here are titled "Setting Shell and Environmental Variables" and "Setting Environmental Variables at Login".  The whole article is pretty good, so I'd recommend reading it in general.

But yeah, try setting your variables up as described there.  That should allow you to remove the changes from `.gitignore` without causing AWS key issues.

**Comment by StlMaris123** [comment]
@rlgreen91, I had a misspelling on the `.bashrc` file that is why it was not being loaded correctly. I have resolved it but still Travis CI doesn't build.  :disappointed:

**Comment by rlgreen91** [comment]
@StlMaris123 if you look at the section outlining which tests passed and failed, there is a "Details" link that you can navigate to find out details of the test run.  In this case, following the "Details" link shows that Travis CI still cannot find your AWS credentials.  At this point, I would try deleting your branch and making your changes on a new one - since you figured out the issue with the credentials, it shouldn't be an issue.  Just close this PR and make a new one when you push the other branch.

In the future, I would look at the "Details" link and see if you can find a solution to the error messages there first before asking one of us.  Rails is popular enough so that you should be able to find suggestions for resolving the error.  Since there's a bit of time between when you post a comment and when one of us responds, hopefully that unblocks things for you a lot of times.

**Comment by StlMaris123** [comment]
Hi @trystant , Isn't build supposed to be updated automatically once I configured the Aws keys?

**Comment by rlgreen91** [comment]
Have you pushed to this branch since then?  If you made your changes in a different branch, that won't be reflected here.

**Comment by trystant** [comment]
Agreed with @rlgreen91. Another push should help.

**Comment by rlgreen91** [comment]
@StlMaris123 Travis is still failing due to missing AWS keys.  If you were able to get Travis to successfully pick up on the keys in another branch, then I would create a new branch and make the changes from here in that branch, pushing it up as a separate PR.  Once you confirm that it works (or at least doesn't complain about AWS keys), then go ahead and close this one.

**Comment by rlgreen91** [comment]
@StlMaris123 do you need any help with the changes I requested?

**Comment by StlMaris123** [comment]
Sorry Rachael, This skipped me. I will look into it. Thanks

**Comment by StlMaris123** [comment]
I will aslo close this, so that I can push directly to EBwiki fork

**Pull request closed without merging**
