### PR TITLE
for #1115: editing the about page as discussed in the issue thread

### PR DESCRIPTION
**Pull request by campgurus**
Revised as discussed.

### CODE REVIEW

**Comment by rlgreen91** [comment]
Can you remove the binary file that got pushed as part of the PR?

**Comment by rlgreen91** [comment]
@campgurus What's the blocker on this?

**Comment by rlgreen91** [comment]
@campgurus What's the blocker on this?  I really just need you to remove the binary files that was included in the PR.

**Comment by campgurus** [comment]
Sorry, just saw these messages.  I removed the file and adjusted gitignore and recommitted.

**Pull request merged**
