### PR TITLE
Updated rack-protection gem

### PR DESCRIPTION
**Pull request by simransinghal**
Issue #1342 
Updated the rack-protection gem.

 1) All tests passed
 2) Can destroy and recreate the database successfully
 3) The site still works correctly

### CODE REVIEW

**Comment by rlgreen91** [comment]
@simransinghal can you add your credentials to Travis and re-run the tests?  PR #1296 has instructions on how to do so.

**Comment by simransinghal** [comment]
@rlgreen91 @trystant I think I don't have required permission to change the environment variable, as I am not getting any settings option [here ](https://travis-ci.org/EBWiki/EBWiki/builds/352044894) on the drop-down button.

**Comment by simransinghal** [comment]
I added, but then also not working.
screenshot from 2018-03-13 12-04-55

**Comment by rlgreen91** [comment]
Hi @simransinghal!  So, I go into a bit more detail in the Slack group, but basically, Travis does not play well with environment variables and forks.  What you'll need to do is open a new PR that comes from a topic branch within EBWiki, not your own fork of the rep.  You should be a collaborator on the repo, but if you get an error saying permission denied when you go to push the code, just let me know.

**Comment by rlgreen91** [comment]
@simransinghal have you had a chance to try redoing this in a topic branch in EBWiki?  If you need any help, just let me know.

**Comment by rlgreen91** [comment]
Since @trystant is covering this in #1492, I'm going to go ahead and close this.

**Pull request closed without merging**
