### PR TITLE
refactor: use partials instead of an each loop for case links and ord…

### PR DESCRIPTION
**Pull request by carloslazo**
Addresses Links out of order #1928 

Links are now ordered using @this_case.links.order('created_at desc') which will result in revers chron order.

It also refactors the links into a collection of partials.

In your PR did you:

  - [ x] Include a description of the changes?
  - [x ] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hi @carloslazo, thanks for making that change.  One last thing to get past the complaint from Bullet - please modify that line to say `includes(...:links).order("links.created_at DESC")

**Comment by carloslazo** [comment]
Hey @rlgreen91 , which line are you referring to?

Is it this one? `@this_case = Case.includes(:comments, :subjects, :links).friendly.find(params[:id])`

**Comment by rlgreen91** [comment]
> Hey @rlgreen91 , which line are you referring to?
> 
> Is it this one? `@this_case = Case.includes(:comments, :subjects, :links).friendly.find(params[:id])`

Yes, that's the one, thanks!

**Comment by carloslazo** [comment]
Made the changes. There are 2 specs failing from user_notifier_spec.rb. I think they may be from somewhere else though since I didn't touch emails.

Let me know. Thanks.

**Comment by rlgreen91** [comment]
Hey @carloslazo, no, you don't have to worry about that failing spec, that's being taken care of separately.  One truly last thing - can you split up the line in the controller that you just changed?  Rubocop is complaining that it's too long.

**Comment by carloslazo** [comment]
> Hey @carloslazo, no, you don't have to worry about that failing spec, that's being taken care of separately. One truly last thing - can you split up the line in the controller that you just changed? Rubocop is complaining that it's too long.

Done! :)

**Pull request merged**
