### PR TITLE
Begin implementation for Services #1674 

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
Re-implement UserObserver as a service object

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hello @rlgreen91 , Am kindly requesting for your help moving forward with this. Am still struggling with services

**Comment by rlgreen91** [comment]
@StlMaris123 Ok, so if you look within app, you should see a folder titled `services`.  With the exception of `service.rb`, each of the files defines a service object - `AddUserToMailchimp`, `DetermineVisitsToCases`, and `SortCollectionOrdinally`.  What you need to do is create a service object like that called, let's say `OnboardUser`.  That object, given a user as the parameter, would be responsible for doing what's outlined in `UserObserver` now - adding them to Mailchimp and sending the email.  Why don't you try making that first - the new file you created is already most of the way there.  You just need to make it look like the other ones in the folder.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I have made some changes. How do we call the service? I tried as a callback but it does not work

**Comment by rlgreen91** [comment]
Ok, a couple of things - it's probably failing because it's not finding the file.  It should be `app/services/onboard_user.rb`, not `app/services/on_board_user.rb`.  The name of the module you're trying to load doesn't match the file name convention Rails is expecting.

The second thing is that this shouldn't be a module - it should be a class.  Lastly, we actually won't call this in the model - instead, we'll call this from the controller.  So what you'll do is call this in the registrations controller.

**Comment by rlgreen91** [comment]
Ok.  Be sure to call the service object from the registrations controller, rather than in the model.  Additionally, also change the name of the file.  Finally, rather than commenting the line in `config/application.rb`, you can just remove it.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , only issue I have in putting it in the registrable controller is getting the user object

**Comment by rlgreen91** [comment]
@StlMaris123 You can still access it there, it's just that Devise calls it a resource in the controller rather an a user.

**Pull request merged**
