### PR TITLE
#2215 changed id to case_slug in routes and cases controller

### PR DESCRIPTION
**Pull request by danuluma**
In your PR did you:

  - [X] Include a description of the changes?
  - [X] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
In the history action, define `@this_case` explicitly using the new value of the parameter.

**Comment by danuluma** [comment]
done

**Comment by rlgreen91** [comment]
In the history action, it should just be `Case.friendly.find`.  What's listed now expects to use a numeric ID rather than a slug.

**Comment by danuluma** [comment]
Ok, let me change that

**Comment by danuluma** [comment]
Hi @rlgreen91, I changed ```Case.friendly.find``` to ```Case.friendly.find_by_slug``` so that it returns ```nil``` when a record isn't found instead of throwing ```ActiveRecord::RecordNotFound``` error

**Comment by rlgreen91** [comment]
@danuluma what exactly was the change to `db/structure.sql`?  If there was none for this PR please remove it.

**Comment by rlgreen91** [comment]
Please merge master into this branch.

**Comment by danuluma** [comment]
I had pending migration error and I ran ```rake db:migrate``` That's why there were changes in ```db/structure.sql```

**Comment by rlgreen91** [comment]
@danuluma Please remove `db/structure.sql` from the PR

**Comment by rlgreen91** [comment]
Well this is awkward - now there's a merge conflict with `db/structure.sql`.  Can you merge master into your branch and push again?

**Pull request merged**
