### PR TITLE
Update rubocop to 0.93

### PR DESCRIPTION
**Pull request by danielvdao**
Issue: https://github.com/EBWiki/EBWiki/issues/3947

Brings rubocop up to 0.75. I could be wrong, but I think we're already running rubocop 0.93 production. [Gemfile.lock in main](https://github.com/EBWiki/EBWiki/blob/main/Gemfile.lock#L694).

When I bash into the container and run `bundle exec rubocop -v` I also see 0.93. That said, I upgraded the `.codeclimate.yml` so that we're running 0.75.

EDIT: After comments, looks like we're bringing it up to 0.93!

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Add and/or update specs for your code?
  - [ ] Update the release tasks script to reflect tasks that should run when deploying to staging or production?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Thanks for tackling this @danielvdao!  Since that's the case, do you mind updating the Gemfile to list 0.93 as the version, and updating `codeclimate.yml` to use that version as well?

**Comment by danielvdao** [comment]
@rlgreen91 done 🙂 . I could be wrong, but I think we also missed the rubocop-performance gem extension. I've also added that in.

**Comment by mnyon-grandkru** [comment]
Hi @danielvdao , thanks for the work on this gem. Looking at the README for [rubocop-performance](https://github.com/rubocop/rubocop-performance), it looks like the recommended way to instantiate it would be to use `require:false` in the `Gemfile`, followed by one of the require techniques outlined in that README.  Would you mind requiring `rubocop-performance` with those techniques?  Thanks.

**Comment by danielvdao** [comment]
Hi @mnyon-grandkru! Thanks for catching that. Total n00bie with the Gemfile so I learned something new today 🙂 . I went ahead and uncommented the `require` in `.rubocop.yml`. I cleaned up some of the rubocop exclusions we had along with removing one.

I turned off the excludes locally and cleaned up some of the specs we had issues with. Other ones would take a little longer so I avoided those for now. Maybe over time I can chip away at them.

**Comment by danielvdao** [comment]
@rlgreen91 @mnyon-grandkru out of curiosity, why don't we have the latest rubocop? I see that we're pinned under the 1.11 major version. I don't see a potential conflict with any of the other gems we have, rubocop-performance is pinned to be under 2.0, but maybe I'm missing something?

**Comment by mnyon-grandkru** [comment]
@rlgreen91 or @managedkaos might have more infromation on this. Updating to 1.11 doesn't disrupt the `bundle install` command, FWIW.

**Comment by danielvdao** [comment]
I see. I think we should update rubocop all the way if possible as some of the changes that were made conflict with the later rubocop versions anyways (e.g. trailing comma in arguments). If we have agreement from @rlgreen91 and you / whomever else we may need it from, I'm happy to own that 🙂.

**Comment by mnyon-grandkru** [comment]
@danielvdao I'm okay with upgrading to 1.11, but I'd put that in a separate issue/ PR. In that way, we can upgrade here as needed and move to 1.11 with everyone's input.

**Comment by danielvdao** [comment]
@mnyon-grandkru Good point, I'm happy to do that separately.

**Comment by mnyon-grandkru** [comment]
@danielvdao It looks like this has a failing spec in this [Github Action](https://github.com/EBWiki/EBWiki/runs/2096377212?check_suite_focus=true_).  Could you look into those and resolve them?

**Comment by danielvdao** [comment]
@mnyon-grandkru that's a previous CI build, no? [This](https://github.com/EBWiki/EBWiki/pull/3979/checks?check_run_id=2096409089) is the most recent one I see 🤔

**Review by rlgreen91 — APPROVED** [review]
LGTM

**Pull request merged**
