### PR TITLE
move undo action in cases controller to versions controller solves #1893

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
move undo action in cases controller to versions controller
-solves #1893
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@StlMaris123 For codeclimate, you can disable the check for too many lines in a method.  However, please add top level documentation as requested.

**Comment by rlgreen91** [comment]
Hmm...so we actually need to account for the fact that in the future we'll be enabling PaperTrail for other models.

Let's nest this under cases in the routes, and move this controller inside of a module `Cases`.  In the routes, rename `:id` to `:case_id` so that it's clear which model this route is nested under.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , Is this what you were talking about?

**Comment by rlgreen91** [comment]
Yes, the only thing left to do is put the controller in a module `Cases`

**Comment by rlgreen91** [comment]
Perfect

**Pull request merged**
