### PR TITLE
Replacing "back" link on pages with button

### LINKED ISSUE #97: Need 'Back to Case' Button on History and Edit Pages
Simple nav button or links would be helpful

### PR DESCRIPTION
**Pull request by rachaelkiteme**
In your PR did you:
Fixes #97 
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [x] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rachaelkiteme** [comment]
New case
new case
New agency
new agency
Edit user
edit user

**Comment by rlgreen91** [comment]
Hey, can you make all of them be on the same line, like you did on the new case page?

**Comment by rachaelkiteme** [comment]
sure

Regards
Rachael

**Comment by rachaelkiteme** [comment]
add case
add case form
New agency
new agency form
Editing user 
update user

**Comment by rlgreen91** [comment]
Ok, last two things - can you arrange the boxes like you do for adding a case?  Where the action is on the left and back/cancel is on the right? Then align the boxes with the right side of the form.

**Comment by rlgreen91** [comment]
@rachaelkiteme What's the status on this PR?  You only need to make two minor changes.

**Comment by rachaelkiteme** [comment]
Was able to place the buttons as requested, However I felt they were a bit apart was trying to find out how to a place them to appear as new case form but didn't get a solution.
agency form

**Comment by rlgreen91** [comment]
@rachaelkiteme Oh no, what I meant was that I wanted the buttons to spaced the way they were in the add case page, just on the right side of the page.  Kind of like justified right instead of left, like how the login and clear buttons are in this picture:

image

Does that make sense?

**Comment by rachaelkiteme** [comment]
Yes


Regards
Rachael

**Comment by rachaelkiteme** [comment]
This looks good, right?
agency
update user page

**Comment by rlgreen91** [comment]
Perfect!  I'll go ahead and merge this.

Actually, it just occurred to me - the buttons should probably be the same colors as the overall scheme.  I believe you already set the different colors as CSS variables.  I would make the green buttons orange and the blue ones light gray, and then just use black for the text throughout.  This [article](https://stackoverflow.com/questions/38528021/bootstrap-change-the-color-of-visited-links) explains how to do it, although you might have to use a custom class in the stylesheets to make it work.

But yeah, let me know when you make the color changes and I'll merge.  Thanks!

**Comment by rachaelkiteme** [comment]
Form Button color
agency user case form

**Comment by rlgreen91** [comment]
Nice!  The white text is a better touch. I'll go ahead and merge.

**Pull request merged**
