### PR TITLE
Add Washington Post to list of admired sites on about page #2540

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
Add Washington Post to list of admired sites on about page
- Solves #2540
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , timestamp is missing on the migration to add calendar events, Could this be why it is not being loaded in the schema?

**Comment by rlgreen91** [comment]
What error message are you getting for it?  It has timestamp information for both a start time and an end time.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 @trystant , checked around and most pull requests are failing with a similar error
```
ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  relation "calender_events" does not exist
       LINE 5:                WHERE a.attrelid = '"calender_events"'::regcl...
```

**Comment by StlMaris123** [comment]
Hi @rlgreen91 @trystant , checked around and most pull requests are failing with a similar error
```
ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  relation "calender_events" does not exist
       LINE 5:                WHERE a.attrelid = '"calender_events"'::regcl...
```

**Comment by StlMaris123** [comment]
Hi @rlgreen91 @trystant , checked around and most pull requests are failing with a similar error
```
ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  relation "calender_events" does not exist
       LINE 5:                WHERE a.attrelid = '"calender_events"'::regcl...
```

**Pull request merged**
