### PR TITLE
Add field title in case form links section

### LINKED ISSUE #1657: Update case form to include field for title in links section (4 of 9)
Note: This issue is 4 of 9 that need to be completed in a particular order for a feature. Each issue should be closed and the corresponding PR merged before the next issue is begun.

Update the case form and controller to include a field for titles in the links section.

### PR DESCRIPTION
**Pull request by rachaelkiteme**
In your PR did you:
Fixes #1657 
This pr updates case form with title field in links section

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [x] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rachaelkiteme** [comment]
case form links section
title field

**Comment by rlgreen91** [comment]
Can you put the URL field above the title field?  We'll be adding some functionality in another issue that makes it better to have it in that order.  And yes, the title field shouldn't be required as of now.

While we're here, can you make sure the orange used for the "Add a Link" button is the same as the one we used elsewhere, that we have a variable for?

**Comment by rlgreen91** [comment]
Sorry, is it the same orange @rachaelkiteme?

**Comment by rachaelkiteme** [comment]
Yes sure, can confirm here #1604

Regards
Rachael

**Comment by rlgreen91** [comment]
Oh, ok, so rather than copy the hex value, just use the variable name we gave it.  `orange` is assigned to that hex number in the stylesheet, so you should be able to just the value to `orange` and confirm that it's the correct color.  Although we didn't set the value of `white`, that is a variable that is automatically added by the processor so you can use that instead of the hex value as well.

**Comment by rlgreen91** [comment]
Why are you modifying `bootstrap-mods.scss`?

**Comment by rachaelkiteme** [comment]
Oh, thats what caused the error!! The reason I changed `bootstrap-mods.scss` is that I thought thats where we do bootstrap modifications.

**Comment by rlgreen91** [comment]
No worries.  No, we currently kinda make the changes in the corresponding stylesheet for the model.  Eventually we'll get around to organizing those a bit more clearly.

**Pull request merged**
