### PR TITLE
refactor drop down in cases controller solves#1653

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
This pr sorts gender using SortCollectionOrdinally.
solves  issue #1653

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I was looking at options we have for removing drop_down from the cases helper. I thought of using a concern but they are used to refactor controllers. I researched on ways to refactor views and its either via helpers or partials. Could we move the method to another helper or we just leave it there?

**Comment by rlgreen91** [comment]
Hey @StlMaris123, so rather than do `Gender.all` in the helper, it should be done in the controller.  This is for the form, if I remember correctly - so if you look at the controller action `new`, you'll see we already pass along instance variables for `agencies`.  We should do the same thing for `genders`.  This will require a change to `cases_controller` and the form.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , did you mean something close to what I have done?

**Comment by rlgreen91** [comment]
Yes, this looks good.

**Pull request merged**
