### PR TITLE
Added case guide subsections

### LINKED ISSUE #967: Add example of added and updated case in guide (2 of 3)
Note: This is issue 2 of 3, and the requested changes must be merged before you can move to the next one in the project.

In the Guide to Contributing to EBWiki, add a section titled "Cases".  This section contains three subsections: one for adding a case, one for updating a case, and another for following and unfollowing a case.  Have a heading for the section, and collapse the subsections by default - selecting the corresponding heading should expand and collapse the subsection.

### PR DESCRIPTION
**Pull request by rachaelkiteme**
In your PR did you:
Fixes #967

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Ah, I guess I was a bit unclear - I'd like for you to add the actual content as well.  Explain how to add a case (including that you should be logged in first!), include screenshots, etc.  Same for editing cases.

**Comment by rachaelkiteme** [comment]
Still there is something that is not so clear, There is this other static
page `guidelines.htm.erb` that has similar content only that the content is
not displayed as you wanted.
When you talked of adding static page contribution guidelines to EBWiki did
you mean contributing to the code base?

Regards
Rachael

**Comment by rlgreen91** [comment]
Hmm, I see what you mean.  I still think we need to have a page on how to use and contribute to the website, separate from a general contribution page that has links to the page I just mentioned, a link to Github, link to donate, etc. 

Tell you what - please copy over the sections on adding a new case and editing a case onto the new page you've made.  Make those the collapsible sections I mentioned in the issue, and add screenshots where you see fit.

**Comment by rlgreen91** [comment]
@rachaelkiteme Is this a WIP?  Would it help for me to make a label for WIP that you can apply for stuff you don't want me to review just yet?

**Comment by rlgreen91** [comment]
@rachaelkiteme What's the status on this PR?

**Comment by rachaelkiteme** [comment]
I did it partly. I had this challenge where once I  `rake db:seed` locally no data is displayed. You were to help on this.

**Comment by rlgreen91** [comment]
Right, I'm looking into that, but...oh.  Okay, so, in general, when you make documentation, you want to make it from the perspective of the person who'll read it, right?  In this case, since this is something that a user will read when learning how to use our site, you'll want to go through the steps on the actual website and make the docs based on that, not your local dev environment.

Depressingly enough, here's a link to a database of potential cases: https://www.washingtonpost.com/graphics/national/police-shootings/.  From there you can find a case to add and one to edit.

**Pull request merged**
