### PR TITLE
Improvements to Documentation and default .env Setup

### PR DESCRIPTION
**Pull request by iarobinson**
### Description:

As I was getting this project running locally, I ran into a few issues which slowed me down. This PR is me adjusting the documentation and the sample files so that future developers can get started a little bit quicker.

#### Improvments:
- Upgrade the .env.example file to have a default server set so new developers don't need to specify a local for elastic search
Currently, the developer needs to adjust the elastic search URL. I just made it so the new developer doesn't need to set it.
- Upgrade README.md with information on how to set up Elasticsearch
If a new developer has never used elastic search before, this could be a point where we loose them.

This PR does not address an issue. It's just what I noticed while getting the app running locally myself.

### CODE REVIEW

**Comment by rlgreen91** [comment]
@iarobinson Hey, this looks good.  Can you resolve the merge conflicts and re-push?

**Comment by managedkaos** [comment]
I think the main cause of the conflicts is that the edits to `docs/SETUP_LOCALLY.md` should now go into `docs/SETUP_LOCALLY_FULL_STACK.md`.

I can help out if you'd like.

**Comment by rlgreen91** [comment]
@iarobinson Wanted to follow up on this - just need to resolve the merge conflicts.

**Comment by rlgreen91** [comment]
I wanted to follow up on this: looking at this now, I'm not completely sure we need these changes.  We have updated `.env.example` in a separate PR to include the default Elasticsearch URL.  However, in terms of instructions on how to set up Elasticsearch, we already point readers to their guides on how to set it up for their environments.  Additionally, this is now the alternative method to running EBWiki locally - we try to steer people towards using the Docker setup instead, which will take care of this for them.  Because of that, I'm going to close this.

**Pull request closed without merging**
