### PR TITLE
test if travis is working

### PR DESCRIPTION
**Pull request by StlMaris123**
This pr is to perform experimental changes until  travis works

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @trystant , you mean I add the environment variables for each step?

**Comment by rlgreen91** [comment]
@StlMaris123 Were you able to add your credentials via your `.bashrc` file?  By the way, there should only be one period, at the beginning of the file name.

**Comment by StlMaris123** [comment]
Hello @rlgreen91 @trystant , Yes I was. Locally my file works fine. I think the reason travis is failing is because the `.bashrc` file where I have put the variables is not being loaded here

**Comment by trystant** [comment]
Hi @StlMaris123.

One doesn't need to load their whole `.bashrc` into Travis. Instead, you can add the specific environmental variables through the [Travis](https://travis-ci.org/EBWiki/EBWiki/builds/346870401) interface.

If you select the "More Options" dropdown on the upper right:
screenshot 2018-02-28 at 01 58 49

and click on "Settings", you'll see the "Environment Variables" section:

screenshot 2018-02-28 at 01 58 32

You can enter the AWS credentials there.

**Comment by StlMaris123** [comment]
Wow, are there any permissions required? To be a contributor maybe? I only have requests on the drop down menu. Sorry to bother you so much.
screenshot from 2018-02-28 10-09-49

**Comment by StlMaris123** [comment]
Hi @trystant  and @rlgreen91 , the build is now working. Just a few tests that are passing that were not caused by this Pr. I have also ran a build for my other pr and the keys are now available. Thank you :smile:

**Comment by StlMaris123** [comment]
Close this pr. Its purpose has been met

**Comment by rlgreen91** [comment]
@trystant did you set up your environment variables in Travis the same way?  Once I added my keys as ENV variables, I never had to update anything on Travis itself.

**Comment by trystant** [comment]
I set up the environment variables on Travis because I have an aversion to
putting individual credentials in version control.

**Comment by rachaelkiteme** [comment]
Just what I needed I struggled with this travis error. Great PR

**Comment by simransinghal** [comment]
@trystant I think I don't have required permission to change the environment variable, as I am not getting any settings option [here ](https://travis-ci.org/EBWiki/EBWiki/builds/352044894) on the drop-down button.

**Comment by rachaelkiteme** [comment]
Hello,

You must be signed in to travis. You can sign in with github, option that
is at the right corner of the page.

Regards
Rachael

**Pull request closed without merging**
