### PR TITLE
enable friendly ids for states #1237 

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
enable friendly ids for states
- Solves #1237
  - [x] Include a description of the changes?
  - [ ] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
That's fine to use name.  But yeah, there's plenty of places where we do call `State.find` or something like that.  That's what you should be replacing - anytime we find an instance of `State` using the ID.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I did a global search, there is nowhere we are doing `State.find`

**Comment by rlgreen91** [comment]
Ah, also, your PR failed in CI because we need to add a `slug` column to states, despite what the docs imply.

**Comment by rlgreen91** [comment]
@StlMaris123 did you run the migration?  There should have been a change to `db/structure.sql` as well.

**Pull request merged**
