### PR TITLE
Refactor conversations this solves fixes#1112

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
This pr refactors new method in conversations controller

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [x] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
@StlMaris123 please update the specs associated with this controller.  You should still successfully pass the spec that says an array is returned for `other_users`, and that it does not contain the `current_user`.

**Comment by StlMaris123** [comment]
Hello @rlgreen91, Please have a look at it now

**Comment by rlgreen91** [comment]
@StlMaris123 this branch has a potential merge conflict.  Please pull the latest version of the master branch, and incorporate that into your topic branch either using `git merge` or `git rebase`.

**Comment by rlgreen91** [comment]
Hey @StlMaris123 uh, what happened to the test file?  I saw where you had added the tests previously, but now that file is missing from the last commit?  Can you add it back?  Once you do that and I do a check on my end it should be good to go.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , @trystant had already updated tests and so when I wrote on my end, there was a merge conflict. The tests have been updated.

**Comment by rlgreen91** [comment]
Ah ok, thanks.  I was just confused because I remembered seeing it at one point.

**Pull request merged**
