### PR TITLE
Update carrierwave-imageoptimizer gem

### PR DESCRIPTION
**Pull request by debashis-biswal**
Update carrierwave-imageoptimizer gem
Fixes: #3795 

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hi @debashis-biswal, so this is like your other PRs, where after making a change in the Gemfile, you'll want to run `bundle install` to force the Gemfile.lock to regenerate properly.

**Comment by rlgreen91** [comment]
Hi @debashis-biswal, can you resolve the merge conflicts on this?  Thanks

**Comment by debashis-biswal** [comment]
> Hi @debashis-biswal, can you resolve the merge conflicts on this? Thanks

@rlgreen91 I will resolve the merge conflicts.

**Comment by mockdeep** [comment]
Looks like this gem is already at the most recent version. Thanks for contributing!

**Pull request closed without merging**
