### PR TITLE
update bin/setup for issue#3383

### PR DESCRIPTION
**Pull request by georgettica**
In your PR did you:

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [x] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [x] Add and/or update specs for your code?

This added a script to check the packages that are installed
No UI changes were made, just a script.
No gems were harmed making this PR (no changes to gems).

I also tried for 4 hours to run the setup script with no luck, please help me build it on your machines.
The code was not touched to the specs are the same.

### CODE REVIEW

**Comment by georgettica** [comment]
I tried to install Ruby 2.5.5 but the installation failed.

I tried to change the script but I didn't understand if it failed because of my script or it just failed

**Comment by georgettica** [comment]
> Thanks for your @georgettica! Quick question: when you say you couldn't get the script to run, are you referring to this setup script or the CI? If it's the latter, then it's fine - there's an issue with how Travis handles environment variables for forks.

I am still waiting for your response.. please help

**Comment by rlgreen91** [comment]
Well @georgettica I can't tell you when it failed - I don't know how you're installing this! :)

Are you trying to run `./bin/setup` and that's failing?  Can you paste the error message if so?
Are you trying to install Ruby before running `./bin/setup` and that's what's failing?  This script assumes Ruby is installed.
Do you mean that when you push your changes to your PR, it'll say that it can't complete the build? As I mentioned above, that's not a concern - Travis is weird about environment variables and forks.

If you provide a bit more info, I can help you figure out what the issue is.

**Comment by rlgreen91** [comment]
> Well @georgettica I can't tell you when it failed - I don't know how you're installing this! :)
> 
> Are you trying to run `./bin/setup` and that's failing? Can you paste the error message if so?
> Are you trying to install Ruby before running `./bin/setup` and that's what's failing? This script assumes Ruby is installed.
> Do you mean that when you push your changes to your PR, it'll say that it can't complete the build? As I mentioned above, that's not a concern - Travis is weird about environment variables and forks.
> 
> If you provide a bit more info, I can help you figure out what the issue is.

@georgettica can you provide more info on the error message please?

**Pull request closed without merging**
