### PR TITLE
Automatically redirect url after case title is updated

### LINKED ISSUE #1106: Automatically redirect URLs after case title is updated
To automatically redirect older case URLs after the case title is updated, add the following if statement to the `show` method in the `articles` controller:

```
# If an old id or a numeric id was used to find the record, then
# the request path will not match the article_path, and we should do
# a 301 redirect that uses the current friendly id.
if request.path != article_path(@article)
   return redirect_to @article, :status => :moved_permanently
end
```

You should be able to test this in the controller specs.

### PR DESCRIPTION
**Pull request by rachaelkiteme**
In your PR did you:
FIxes #1106
  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by rlgreen91** [comment]
I believe `@case` should be `@this_case` - that should fix Travis. Please add the feature spec when you get a chance.

**Comment by rlgreen91** [comment]
@rachaelkiteme for codeclimate, don't worry about the identical blocks for undo and redo links.  Just make the change to use a guard clause in line 41 for cases controller.

**Comment by rachaelkiteme** [comment]
Am redoing the specs

**Comment by rlgreen91** [comment]
@rachaelkiteme What's the status on this PR?

**Comment by rachaelkiteme** [comment]
Ready for review.

**Comment by rlgreen91** [comment]
Where are the specs?

**Comment by rlgreen91** [comment]
@rachaelkiteme What's the status on this PR?  You said that the specs are done but they aren't included in the files listed above.

**Comment by rachaelkiteme** [comment]
Hi @rlgreen91 , am trying test the redirect given the condition ` request.path != case_path(@this_case)` but the `response.status` is a 200, because its displays the status when the page is rendered, which is a success. Please guide me on how to do the test.

**Comment by rlgreen91** [comment]
@rachaelkiteme I would add an assertion to that test verifying that the title of the page after the redirect is the new title for the case.  At that point it's passed.

**Comment by rachaelkiteme** [comment]
Still not getting it right, cause am getting same output. Maybe you can help with a reference link?

**Comment by rlgreen91** [comment]
You could try testing for the redirect here: https://stackoverflow.com/questions/10955474/how-to-test-for-a-redirect-with-rspec-and-capybara/28986777

Or, you could assert that there is a div containing the updated title present on the page.  Can you push your code for the specs?  I can't really advise you on a spec that I can't see.

**Comment by rlgreen91** [comment]
@rachaelkiteme what's the status on this PR?

**Comment by rlgreen91** [comment]
Hey, so for the feature spec, it's not so much that we need to test IDs work - rather, what we need is a spec that tests that if we access a case using it's old title, that we'll be redirected to the case page.  Does that make sense?

**Comment by rachaelkiteme** [comment]
Yes, sure it does.
Have a question, why is it that when we run `visit "/cases/#{this_case.id}"` on the console it returns `nil`?

**Comment by rlgreen91** [comment]
It's most likely because you're no longer in the test environment.

**Comment by rlgreen91** [comment]
@rachaelkiteme What's going on with this PR?  Do you need help with anything?

**Comment by rachaelkiteme** [comment]
Yes, I do will be very grateful, was looking at it yesterday but the output
is still disappointing, Did I add the changes in the right way?
Regards
Rachael

**Comment by rlgreen91** [comment]
Ok, so here's some pseudocode:

```
create a case and navigate to the page
save title of case as "old title"
update case title and save new title as "new title"
visit '/cases/old_title'
verify assertion that you are redirected to page with url '/cases/new_title'
```

To verify the assertion, you can use something like `expect(current_path) to equal 'cases/new_title'`

**Comment by rlgreen91** [comment]
Ah, let's change that last line to be `expect(page).to have_current_path('/cases/new-title')` - using that matcher will trigger Capybara's waiting behavior, which should be long enough for the redirect

**Comment by rlgreen91** [comment]
Great!  One last thing - can you merge master into this branch?  I suspect there's a couple of things that have changed, particularly with that `before_filter`

**Comment by rlgreen91** [comment]
Okay, thanks for adding master in.  One thing to note - we still want to make sure that we're not defining instance variables in private methods.  Update `find_case` to work the way `load_commentable` does in the comments controller, and remove the `before_filter`.

**Comment by rlgreen91** [comment]
Why are you returning in the `show` action?  That's not going to execute the rest of the code at all.

**Comment by rlgreen91** [comment]
@rachaelkiteme What's the status on this PR?

**Comment by rachaelkiteme** [comment]
Am getting this error and I know how to go about it 
```Bullet::Notification::UnoptimizedQueryError:
       user: rirrie
       GET /cases/old-title
       AVOID eager loading detected
         Case => [:comments, :subjects]
         Remove from your finder: :includes => [:comments, :subjects]
       Call stack
         /home/rirrie/EBWiki/spec/features/user_visits_case_page_spec.rb:9:in `block (2 levels) in <top (required)>```

**Comment by rlgreen91** [comment]
If you run into an error, please push the code to the PR.  Otherwise it's difficult to see what exactly the issue is.  At best guess, I would say you could try using a `where` or `find_by` clause would allow you to still do the eager loading.  Searching for how to use `includes` with friendly_id should turn up some good results.

**Comment by trystant** [comment]
I'm going to close this PR out and re-apply the lessons learned in a new branch.

**Pull request closed without merging**
