### PR TITLE
New Pull request

### PR DESCRIPTION
**Pull request by shashank76**
#2646

### CODE REVIEW

**Comment by rlgreen91** [comment]
Why is this a separate PR?

**Comment by rlgreen91** [comment]
@shashank76 are you still planning to work on this?  If so, please respond by December 15.  Otherwise, I will close this PR.

**Comment by rlgreen91** [comment]
@shashank76 Please merge master into this branch.  Additionally, be sure to resolve any CodeClimate issues.

**Comment by shashank76** [comment]
Conflicts resolved. Check and merge pull request.

**Comment by trystant** [comment]
I'm letting this PR die in favor of starting up a new branch with specific changes.

**Pull request closed without merging**
