### PR TITLE
Shoulder matchers #1646 

### PR DESCRIPTION
**Pull request by StlMaris123**
In your PR did you:
This pr refactors model tests to use shoulder matchers

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [x] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
For some reason using shoulda matchers on uniqueness validation fails, this is what I had
```
it { should validate_uniqueness_of(:name).ignoring_case_sensitivity.with_message('An agency with this name already exists and can be found. If you'\
              ' want to create a new agency, it must have a unique name.') }
```

**Comment by rlgreen91** [comment]
Can you post the stack trace for the failing test?

**Comment by StlMaris123** [comment]
` should validate that :name is unique, producing a custom validation error on failure (FAILED - 1)`

**Comment by StlMaris123** [comment]
I have not included it in this pr

**Comment by rlgreen91** [comment]
Can you add it?  It should cause CI to fail, and then I can take a look at the stack trace.

**Comment by rlgreen91** [comment]
@StlMaris123 In this branch, run `bundle install` to update your Gemfile.lock and then push that to fix Travis.

**Pull request merged**
