### PR TITLE
Update Geocoder gem

### PR DESCRIPTION
**Pull request by jaquesdias**
Update geocoder gem to the latest version. Reference: #3816 

In your PR did you:

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] ~Include screenshots of any changes to the UI?~
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] ~Add and/or update specs for your code?~

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hey @jaquesdias, thanks for contributing!  So, somehow, there are no changed files?  Weird.  Do you mind pulling down the latest version of main and merging that into your branch and push it up again?  Maybe that'll trigger the difference.

**Comment by mockdeep** [comment]
@jaquesdias Closing for now, as there aren't any changes. Happy to walk you through it if you'd like to have another go at it.

**Comment by rlgreen91** [comment]
@mockdeep Please don't close other people's PRs.  If there's a PR that you think should be closed, then just leave a comment explaining why, and either ping myself or @trystant.

**Comment by mockdeep** [comment]
@rlgreen91 Okay, sorry about that.

**Pull request closed without merging**
