### PR TITLE
implement rails_real_favicon

### PR DESCRIPTION
**Pull request by kusumandaru**
In your PR did you:

  - [X ] Include a description of the changes?
implement rails_real_favicon
  - [X ] Mention the issue the PR addresses?
Add and update favicons for site #3401 
  - [X] Include screenshots of any changes to the UI?
image
  - [ ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
this pr included mandatory gem to generate favicon, so it hard to separate
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by kusumandaru** [comment]
image
seems PR from forked repository cannot set encrypted environment variable
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by trystant** [comment]
@kusumandaru Correct. You've been invited as a collaborator on this repo. Once you accept, the Travis build should work.

**Comment by rlgreen91** [comment]
@kusumandaru thanks for your contribution!  What image did you use for this?  It has to be a certain size for the site I linked to work, and I only sent the correct image to the guy assigned to the issue.  I've attached it here

EBWikiLogo1200x630

**Comment by kusumandaru** [comment]
> @kusumandaru thanks for your contribution! What image did you use for this? It has to be a certain size for the site I linked to work, and I only sent the correct image to the guy assigned to the issue. I've attached it here
> 
> EBWikiLogo1200x630

i use old logo, i will update it using this image

**Comment by kusumandaru** [comment]
> @kusumandaru Correct. You've been invited as a collaborator on this repo. Once you accept, the Travis build should work.

even already accepted, i still got `ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key`

**Pull request merged**
