### PR TITLE
Add admin specs #1796 

### PR DESCRIPTION
**Pull request by StlMaris123**
- create records using factory bot
- Add admin specs
- solves #1796

In your PR did you:

  - [x] Include a description of the changes?
  - [x] Mention the issue the PR addresses?
  - [ ] Include screenshots of any changes to the UI?
  - [x] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
  - [ ] Add and/or update specs for your code?

### CODE REVIEW

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I have an issue with the block testing `send_followers_email`, kindly help on how to go about it

**Comment by rlgreen91** [comment]
What exactly is the issue?

Travis is hung up on the Gemfile.  Run bundle install inside this branch and push the updated Gemfile.lock to get it to work.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , on `send_followers_email`, I have tried the following:
- `let(:this_case) { FactoryBot.create(:case) }`, which fails with `undefined method `whodunnit' for nil:NilClass`
- `let(:this_case) { mock_model Case, title: 'John Smith', content: 'some content', state_id: 33 }` fails with 
`undefined method `ansi_code' for nil:NilClass`
- `let(:this_case) { FactoryBot.create(:case, title: 'John Smith', content: 'some content', state_id: 33) }` fails with ` undefined method `content=' for #<Case:0x0000000cfa58c8>
       Did you mean?  concern`

**Comment by StlMaris123** [comment]
@rlgreen91 , with that I get `undefined method `ansi_code' for nil:NilClass`, for both:\
- `let(:this_case) { FactoryBot.create(:case, state_id: 33) }`
- `let(:this_case) { FactoryBot.create(:case, title: 'John Smith', overview: 'some content', state_id: 33) }
    let(:mail) { UserNotifier.send_followers_email([follower], this_case) }`

**Comment by rlgreen91** [comment]
@StlMaris123 Had you tried to seed the database recently?  That might be the issue - I'm looking into why that's failing in a bit.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , Yes I have

**Comment by rlgreen91** [comment]
Where are you making those statements?  I looked at the code you pushed up and I don't see them in the spec.

**Comment by rlgreen91** [comment]
Ok, so when you create the case, you need to pass along the user value.  If you look at the failing tests in Travis, they're failing because when it creates the email, it doesn't see a user associated with the version.  But we don't actually pass along a user when we create the case.  Try something like `let(:case) { user.cases.create! attributes_for(:case) }`.  That should make the proper association.

**Comment by StlMaris123** [comment]
HI @rlgreen91 , that does not work either, I get undefined method ansi_code for nil:Nil class

**Comment by rlgreen91** [comment]
Even when you create the state beforehand?

**Comment by rlgreen91** [comment]
Hmm, let me look into this one.  I have an idea but I'm not sure if it'll work out.

**Comment by rlgreen91** [comment]
Also - try removing the line disabling PaperTrail.

**Comment by rlgreen91** [comment]
@StlMaris123 what's the status of this PR?

**Comment by StlMaris123** [comment]
Hi @rlgreen91 no progress made, will look at it tomorrow. Was trying to help out Rachael with the tests

**Comment by rlgreen91** [comment]
No worries.  There's a conflict, so merge master into this branch when you get a chance.

**Pull request merged**
